<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>TurboPort.Launch</RootNamespace>
    <AssemblyName>TurboPort.Launch</AssemblyName>
    <StartupObject>TurboPort.Program</StartupObject>
    <!-- ApplicationIcon>Icon.ico</ApplicationIcon -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TurboPort\TurboPort.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AndroidActivity.cs" />
    <Compile Remove="Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <MonoGameContentReference Include="Content\Content.mgcb" />
    <None Update="Icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
