<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>TurboPort.Test</RootNamespace>
    <AssemblyName>TurboPort.Test</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="FakeItEasy" Version="8.3.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="protobuf-net" Version="3.2.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TurboPort\TurboPort.csproj" />
  </ItemGroup>

</Project>
